### ISSUE TITLE
correct H1 headings issued 

### ISSUE THREAD

**Issue by akaronski** [p1ho/accessibility-checker#6] opened 2020-03-18 11:30 UTC
Hi, right know the headings checker issues h1 headings that are placed in header and footer.

So if you use h1 in the header, one in the body and one in the footer, the checker will always issue all of them and recommend to check and use only allowed headings 2, 3, 4 ... 

Additionally the very first h1 is being issued as not allowed but do you know why exactly? It is a generic text but it is meant to be used as header. Is there a way to output an explenation why something was issued as error in addition to the improvement part?

In order to compare the results I used the AXE accessibility checker that google etc. is using and axe seperates header, body and footer from each other. So maybe letting the checker seperate between header body and footer would be an useful improvement?

**Comment by p1ho** [comment] 2020-03-19 19:26
Hello, thanks for opening this issue!

What you're looking for is the setting for `heading_shift` for Heading Structure Checker.
By default it is [set to 1](https://github.com/p1ho/accessibility-checker/blob/master/src/HeadingStructure/Checker.php#L63)
If you want to allow `<h1>` in the block of html you're testing, then override that value to 0.
(I could try to make the documentation clearer when I'm free)

The reason why it defaults to 1 when I wrote it was, you can imagine for WordPress or Drupal, the way they store a page's data can be visualized like the following:
```JavaScript
{
  "title": "the-page-title",
  "content": "<p>actual html that will get rendered</p>",
  //... some other fields
}
```
Then when a visitor visits that page, WordPress or Drupal will know to put the title field in a `<h1>` in the html at the appropriate place that's returned to the visitor's browser.
So, because h1 is commonly reserved for the "title" field, I have the `heading_shift` default to 1.

The second piece of the puzzle is, it is recommended to have only 1 `<h1>` tag on any given webpage as explained on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements).
> You should only use one `<h1>` per page. Using more than one will not result in an error, but using only one is seen as a best practice.

**Comment by akaronski** [comment] 2020-03-20 14:52
Thanks for your quick answer. In checker.php I have set:
```
public function __construct(int $heading_shift = 0, bool $is_strict = false)
    { 
...
}
```
The problem seems to be, as I mentioned before, that I have one h1 in header, body and footer. You said it is recommended to have only one h1 tag on any given webpage. I think there is no absolute right answer about that and it is kind of a philosophy what you think is the best solution.

Here are some ressources why i came to conclusion that using multiple h1 could be usefull:

- Google Webmasters: No problem about multiple H1, it is common - https://www.youtube.com/watch?v=zyqJJXWk0gk 

- https://www.accessibility-developer-guide.com/examples/headings/multiple-h1-okay-for-seo/

and also:

-  https://www.accessibility-developer-guide.com/examples/headings/visually-hidden-headings/ (Basically here its said that the page title “<head><title>” is actually the main title, not H1. Also since HTML5 it’s clear which H1 is part of “<main>” content and which are part of a banner, footer or what not. So it’s pretty semantic.)

I have tested those accessibility tools for that issue and they were fine about my multiple h1's:

- Google DevTools Accessibility Audit

- AXE

- WAVE

- HTML_CodeSniffer

- Microsoft Accessibility Insights for Web

I don't know how complicated it would be to make it somehow configurable whether you want to allow multiple h1's or not but maybe it would be a nice addition to your current work which I really appreciate :) 

For my personal usage I think I will just ignore this specific error log entry at the moment since its not a standard but a recommendation and this specific part of the page works as supposed to with multiple h1's and has been approved so far.

**Comment by p1ho** [comment] 2020-03-20 15:00
Gotcha, thank you for sharing those resources. I'm not against adding an option that could turn multiple h1 checking off. I can tackle this when I'm free.

**Comment by p1ho** [comment] 2020-03-25 01:52
@akaronski I've released [0.2.2](https://github.com/p1ho/accessibility-checker/releases/tag/0.2.2) which allows setting `allow_multiple_h1` for the Heading Structure Checker. Please try it out and let me know if there are issues.

You'd initialize your Checker like this (assuming no strict mode):
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use P1ho\AccessibilityChecker\HeadingStructure;
$heading_structure_checker  = new HeadingStructure\Checker(0, false, true);
```

Will keep issue open until confirmed everything is working as expected.

**Comment by akaronski** [comment] 2020-03-25 12:14
Thanks for the quick fix. 
I tested the new option and so far I saw that the error message is another now. It says now to try to nest the heading shallower. The following h2 and h3 headings underneath the h1 that has been issued are also shown as too deep. 
I will have some changes made in the structure of the html today and tomorrow then I'll retest it again maybe the h2 and h3 problem is on my side.
But at the moment the very first h1 is correct and the other two h1's are issued as too deep.

**Comment by akaronski** [comment] 2020-03-25 12:20
Regarding the h2 and h3 problem:
If the second h1 is issued as too deep, does the validator issue the following h2 and h3 automatically as too deep too? Because it expects to be h2, h3 and h4 instead?

**Comment by p1ho** [comment] 2020-03-25 14:46
Do you have a sample html? It'll help me explain how it works internally and I can add that to the test cases.

**Comment by akaronski** [comment] 2020-03-25 16:06
I have rebuilt the log in page that suffers the described issue, there you can see the structure of three h1's. Hope this helps somehow. 
I cant upload a .html file so you will have to save it as one.
[examplehtml.txt](https://github.com/p1ho/accessibility-checker/files/4381994/examplehtml.txt)

**Comment by p1ho** [comment] 2020-03-25 19:19
It helps, I will take a look and get back to you when I'm free. Thanks!

**Comment by p1ho** [comment] 2020-03-28 04:06
@akaronski Sorry for the delay, I was finally able to get around to it.
This is what I'm getting when I try to run your example through the checker (I appreciate the welcome message haha)
```
array(2) {
  ["passed"]=>
  bool(false)
  ["errors"]=>
  array(4) {
    [0]=>
    object(stdClass)#40 (5) {
      ["type"]=>
      string(16) "heading too deep"
      ["tag"]=>
      string(2) "h1"
      ["text"]=>
      string(19) "Welcome® dear p1ho"
      ["html"]=>
      string(83) "<h1 id="skip-to-main-content" tabindex="-1">Welcome<sup>&reg;</sup> dear p1ho </h1>"
      ["recommendation"]=>
      string(35) "Try nesting this heading shallower."
    }
    [1]=>
    object(stdClass)#24 (5) {
      ["type"]=>
      string(16) "heading too deep"
      ["tag"]=>
      string(2) "h2"
      ["text"]=>
      string(5) "Login"
      ["html"]=>
      string(45) "<h2 class="h3 form-signin-heading">Login</h2>"
      ["recommendation"]=>
      string(35) "Try nesting this heading shallower."
    }
    [2]=>
    object(stdClass)#7 (5) {
      ["type"]=>
      string(16) "heading too deep"
      ["tag"]=>
      string(2) "h2"
      ["text"]=>
      string(12) "Welcome® !!"
      ["html"]=>
      string(47) "<h2 class="h3">Welcome<sup>&reg;</sup> !! </h2>"
      ["recommendation"]=>
      string(35) "Try nesting this heading shallower."
    }
    [3]=>
    object(stdClass)#20 (5) {
      ["type"]=>
      string(16) "heading too deep"
      ["tag"]=>
      string(2) "h1"
      ["text"]=>
      string(6) "Footer"
      ["html"]=>
      string(31) "<h1 class="sr-only">Footer</h1>"
      ["recommendation"]=>
      string(35) "Try nesting this heading shallower."
    }
  }
}
```
The checker aims to force all headings of the same rank to be at the same nesting level.
The nesting level is set by the first one the checker encounters when parsing from top to bottom.

Explanation for each error:

- `<h1>Dear p1ho</h1>` shows up because where `<h1>` is supposed to be already established by `<h1 class="sr-only">Header</h1>` which is nested much shallower.

- `<h2>Login</h2>` shows up because where `<h2>` is supposed to be already established by `<h2>Main Navigation</h2>` which is nested shallower.

- `<h2>Welcome<sup>&reg;</sup> !! </h2>` is the same reasoning as above.

- `<h1 class="sr-only">Footer</h1>` is the same reasoning as the first one.

But, also note that you raise a good point about there not being a right answer because internet is not perfect and user agents are getting increasingly better at dealing with different kinds of heading structures, this checker is made with the opinion that we should do what we can on our end.

**Comment by p1ho** [comment] 2020-04-16 23:58
Closing the issue for now, feel free to reopen or open a separate issue if something else comes up!

**Closed as completed by p1ho** 2020-04-16 23:58 UTC
